name: Publish to npm

on:
  create:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Publish to npm
      run: |
        tag=$(git describe --tags --abbrev=0)
        sed -i 's/"name": "whatsapp-web.js"/"name": "whatsapp-web.js.zbs"/' package.json
        sed -i "s/\"version\": \".*\"/\"version\": \"$tag\"/" package.json
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
        npm publish